json.id order.id
json.restaurant_id order.restaurant_id
json.total_value order.total_value
json.status order.status
json.city order.city
json.street order.street
json.neighborhood order.neighborhood
json.number order.number
json.complement order.complement